"use client";
import {useState} from "react";
import {ArrowRight,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {ArtworkPlaceholder} from "@/components/common/ArtworkPlaceholder";
import {NetworkMap} from "@/components/network/NetworkMap";
import {ProfileSheet} from "@/components/network/ProfileSheet";
import {SignalRow} from "@/components/signal/SignalRow";
import {OpportunitySheet} from "@/components/signal/OpportunitySheet";
import {AskMatchOffer} from "@/components/flows/AskMatchOffer";
import {SearchPalette} from "@/components/search/SearchPalette";
import {gatherings,people,signals} from "@/data/seed";
import {toggleSavedSignal,useDemoStoreSnapshot} from "@/lib/demoStore";
export function CommonsPage(){
 const store=useDemoStoreSnapshot();const[query,setQuery]=useState("");const[searchOpen,setSearchOpen]=useState(false);const[personId,setPersonId]=useState<string>();const[signalId,setSignalId]=useState<string>();const allSignals=[...store.approvedSignals,...signals];
 return <>
 <section className="relative mx-auto max-w-[96rem] px-5 pb-10 pt-7 sm:px-8 lg:px-14 lg:pb-16 lg:pt-10"><div className="hero-composition"><div className="hero-photo"><img src="/art/02-student-workshop.webp" alt="Concept photograph of students building together around hardware, sketches and laptops." width={1536} height={1024} className="h-[280px] w-full object-cover md:h-[530px]" fetchPriority="high"/></div><div className="hero-panel"><p className="section-kicker">Williams in Technology</p><h1 className="mt-4 font-serif text-[2.7rem] leading-[1.12] text-primary lg:text-[3.65rem]">Extraordinary connections<br className="hidden xl:block"/> start here.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed">From Williamstown to what’s next. Find your people, share an opportunity, and build something together.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild className="pill"><a href="/network">Explore the Network<ArrowRight/></a></Button><Button asChild variant="outline" className="pill border-primary text-primary"><a href="/signal">Open The Signal</a></Button></div><form className="mt-7 flex border-b-2 border-primary" onSubmit={e=>{e.preventDefault();setSearchOpen(true);}}><label className="sr-only" htmlFor="commons-search">Search sample community</label><input id="commons-search" value={query} onChange={e=>setQuery(e.target.value)} className="min-h-12 min-w-0 flex-1 bg-transparent pr-2 text-base outline-none" placeholder="Find people, opportunities, ideas…"/><Button variant="ghost" size="icon" type="submit" aria-label="Search"><Search/></Button></form></div></div><p className="mt-4 text-right font-mono text-xs text-muted-foreground">COMMUNITY PREVIEW · SAMPLE DATA & CONCEPT IMAGERY</p></section>
 <section className="mx-auto grid max-w-[96rem] gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:px-14"><div><p className="section-kicker">People make the difference</p><h2 className="section-heading mt-4">An Eph is closer<br/>than you think.</h2><p className="my-5 max-w-lg text-muted-foreground">Explore the people, places, and expertise across our community. A question in Williamstown can find an answer in Boston, New York, or San Francisco.</p><Button asChild className="pill mb-8"><a href="/network">Meet the community<ArrowRight/></a></Button><div className="border-t-4 border-highlight pt-4"><p className="section-kicker mb-4">Open doors · The Signal</p>{allSignals.slice(0,2).map(item=><SignalRow key={item.id} compact signal={item} saved={store.savedSignalIds.includes(item.id)} onOpen={()=>setSignalId(item.id)} onSave={()=>toggleSavedSignal(item.id)}/>)}</div></div><NetworkMap onPerson={setPersonId}/></section>
 <section className="mx-auto max-w-[96rem] px-5 py-10 sm:px-8 lg:px-14"><ArtworkPlaceholder slot="landscape" className="h-64 rounded-sm sm:h-96"/></section><AskMatchOffer onPerson={setPersonId}/>
 <section className="mx-auto max-w-[96rem] px-5 py-14 sm:px-8 lg:px-14"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker">Opportunities worth passing along</p><h2 className="section-heading mt-3">Happening in the community</h2></div><Button asChild className="pill"><a href="/signal">More signals<ArrowRight/></a></Button></div>{allSignals.slice(2,6).map(item=><SignalRow key={item.id} signal={item} saved={store.savedSignalIds.includes(item.id)} onOpen={()=>setSignalId(item.id)} onSave={()=>toggleSavedSignal(item.id)} fresh={item.locallyApproved}/>)}</section>
 <section className="bg-surface"><div className="mx-auto grid max-w-[96rem] items-center gap-10 px-5 py-14 sm:px-8 lg:grid-cols-2 lg:px-14"><ArtworkPlaceholder slot="dinner" className="h-80 rounded-sm sm:h-[420px]"/><div className="max-w-xl lg:px-8"><p className="section-kicker">Around the table</p><h2 className="section-heading mt-4">You belong here.</h2><p className="my-6 text-lg leading-relaxed">Small dinners. Open work sessions. Honest conversations about the things we’re building—and the things we’re still figuring out.</p><Button asChild className="pill"><a href={`/gatherings?open=${gatherings[0].id}`}>Explore the founder dinner<ArrowRight/></a></Button><p className="mt-4 font-mono text-xs text-muted-foreground">OCT 8 · SAN FRANCISCO · PROPOSED GATHERING</p></div></div></section>
 <section className="mx-auto max-w-[96rem] px-5 py-14 sm:px-8 lg:px-14"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><h2 className="section-heading">Ideas in the making</h2><a href="/resources" className="flex min-h-11 items-center gap-3 font-semibold text-primary hover:underline">Read the field notes<ArrowRight className="size-4"/></a></div><div className="grid gap-6 md:grid-cols-2"><a href="/resources" className="group"><ArtworkPlaceholder slot="collage" className="h-72 sm:h-96"/><h3 className="mt-5 font-serif text-2xl text-primary group-hover:underline">Notes, knowledge, and useful beginnings.</h3></a><a href="/gatherings" className="group"><ArtworkPlaceholder slot="workspace" className="h-72 sm:h-96"/><h3 className="mt-5 font-serif text-2xl text-primary group-hover:underline">Bring the work in progress.</h3></a></div></section>
 <SearchPalette open={searchOpen} onOpenChange={setSearchOpen} initialQuery={query}/><ProfileSheet person={people.find(p=>p.id===personId)} open={!!personId} onOpenChange={open=>!open&&setPersonId(undefined)}/><OpportunitySheet signal={allSignals.find(s=>s.id===signalId)} open={!!signalId} onOpenChange={open=>!open&&setSignalId(undefined)}/>
 </>;
}
