"use client";
import { useDetailState } from "@/lib/useDetailState";
import { useMemo, useState } from "react";
import { Grid2X2, List, Search } from "lucide-react";
import { PageIntro } from "@/components/common/PageIntro";
import { FilterBar } from "@/components/common/FilterBar";
import { EmptyState } from "@/components/common/EmptyState";
import { PersonCard } from "@/components/network/PersonCard";
import { StartupSheet } from "@/components/network/StartupSheet";
import { ProfileSheet } from "@/components/network/ProfileSheet";
import { NetworkMap } from "@/components/network/NetworkMap";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cityName, cities, expertiseOptions, people, startups } from "@/data/seed";
import { toggleSavedPerson, useDemoStoreSnapshot } from "@/lib/demoStore";
import type { CityId, Expertise, PersonKind } from "@/types/domain";

export function NetworkPage() {
  const [personId,setPersonId]=useDetailState();const closeDetail=()=>setPersonId(undefined);
  const store = useDemoStoreSnapshot(); const [query, setQuery] = useState(""); const [city, setCity] = useState<CityId | "all">("all"); const [expertise, setExpertise] = useState<Expertise | "all">("all"); const [kind, setKind] = useState<PersonKind | "all">("all"); const [mentorship, setMentorship] = useState(false); const [view, setView] = useState<"list" | "network">("list"); 
  
  const filtered = useMemo(() => people.filter((person) => { const text = `${person.name} ${person.role} ${person.bio} ${person.expertise.join(" ")} ${person.asks.join(" ")} ${person.offers.join(" ")}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (city === "all" || person.city === city) && (expertise === "all" || person.expertise.includes(expertise)) && (kind === "all" || person.kind === kind) && (!mentorship || person.mentorship); }), [query, city, expertise, kind, mentorship]);
  const selectedStartup = startups.find(startup => startup.id === personId);
  const selected = people.find((person) => person.id === personId);
  const clear = () => { setQuery(""); setCity("all"); setExpertise("all"); setKind("all"); setMentorship(false); };
  return <><PageIntro number="02" eyebrow="People / Startups / Communities" title="The Network" description="Search twelve fictional profiles and four sample startups by place, practice, stage, and the help someone can offer." />
    <section className="sticky top-[9.5rem] z-30 border-b border-primary bg-paper/95"><div className="mx-auto max-w-[96rem] space-y-3 px-4 py-4 sm:px-6 lg:px-10"><div className="flex flex-wrap gap-2"><div className="relative min-w-[16rem] flex-1"><Search className="absolute left-3 top-3.5 size-4" /><Input aria-label="Search people" value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 rounded-sm pl-10" placeholder="Search people, roles, asks, or offers" /></div><Button variant={mentorship ? "default" : "outline"} aria-pressed={mentorship} className="min-h-11 rounded-sm" onClick={() => setMentorship((value) => !value)}>Offers mentorship</Button><div className="flex"><Button size="icon" variant={view === "list" ? "default" : "outline"} className="min-h-11 min-w-11 rounded-none rounded-l-sm" onClick={() => setView("list")} aria-label="List view"><List /></Button><Button size="icon" variant={view === "network" ? "default" : "outline"} className="min-h-11 min-w-11 rounded-none rounded-r-sm" onClick={() => setView("network")} aria-label="Network view"><Grid2X2 /></Button></div></div><div className="flex flex-wrap gap-3"><FilterBar label="City" options={cities.map((item) => ({ value: item.id, label: item.shortName }))} value={city} onChange={setCity} /><FilterBar label="Role" options={(["student", "alumni", "founder"] as const).map((item) => ({ value: item, label: item }))} value={kind} onChange={setKind} /></div><label className="flex items-center gap-3 font-mono text-xs uppercase text-muted-foreground">Expertise<select value={expertise} onChange={(event) => setExpertise(event.target.value as Expertise | "all")} className="h-11 min-w-52 rounded-sm border border-input bg-paper px-3 text-sm normal-case text-foreground"><option value="all">All expertise</option>{expertiseOptions.map((item) => <option key={item}>{item}</option>)}</select></label></div></section>
    <section className="mx-auto max-w-[96rem] px-4 py-8 sm:px-6 lg:px-10"><div className="flex justify-between border-b border-primary pb-3"><p className="font-mono text-xs uppercase">{filtered.length} people</p><p className="font-mono text-xs text-muted-foreground">{startups.length} sample startups</p></div>{view === "network" ? <div className="mt-6"><NetworkMap onPerson={setPersonId} visiblePeople={filtered} /></div> : filtered.length ? filtered.map((person) => <PersonCard key={person.id} person={person} saved={store.savedPersonIds.includes(person.id)} onOpen={() => setPersonId(person.id)} onSave={() => toggleSavedPerson(person.id)} />) : <div className="mt-6"><EmptyState title="No one matches those filters." body="Try another city, broaden the expertise, or clear the mentorship filter." action={{ label: "Clear filters", onClick: clear }} /></div>}</section><section className="border-t border-primary bg-lilac"><div className="mx-auto max-w-[96rem] px-4 py-10 sm:px-6 lg:px-10"><h2 className="font-serif text-4xl text-primary">Sample startups</h2><div className="mt-6 grid gap-px border border-primary bg-primary md:grid-cols-2">{startups.map((startup) => <article key={startup.id} className="bg-paper p-5"><p className="font-mono text-xs uppercase text-muted-foreground">{startup.stage} · {cityName(startup.city)}</p><button onClick={()=>setPersonId(startup.id)} className="text-left hover:underline"><h3 className="mt-2 font-serif text-3xl text-primary">{startup.name}</h3></button><p className="mt-3 text-sm text-muted-foreground">{startup.summary}</p></article>)}</div></div></section><StartupSheet startup={selectedStartup} open={!!selectedStartup} onOpenChange={open=>!open&&closeDetail()}/><ProfileSheet person={selected} open={Boolean(selected)} onOpenChange={(open) => !open && closeDetail()} /></>;
}

