"use client";
import {useState} from "react";
import { useDetailState } from "@/lib/useDetailState";
import {ArrowUpRight,Search} from "lucide-react";
import {PageIntro} from "@/components/common/PageIntro";
import {ArtworkPlaceholder} from "@/components/common/ArtworkPlaceholder";
import {Tag} from "@/components/common/Tag";
import {EmptyState} from "@/components/common/EmptyState";
import {ResourceSheet} from "@/components/resources/ResourceSheet";
import {Input} from "@/components/ui/input";
import {resources} from "@/data/seed";
export function ResourcesPage(){const [id,setId]=useDetailState();const closeDetail=()=>setId(undefined);const[q,setQ]=useState("");const selected=resources.find(r=>r.id===id);const filtered=resources.filter(r=>`${r.title} ${r.category} ${r.summary}`.toLowerCase().includes(q.toLowerCase()));return <><PageIntro number="05" eyebrow="Field notes / Shared knowledge" title="Resources" description="Practical guides, hard-earned lessons, and generous starting points. Sample community resources sit alongside clearly marked official Williams reading."/><section className="mx-auto max-w-[96rem] px-4 py-8 sm:px-6 lg:px-10"><div className="relative mb-8 max-w-xl"><Search className="absolute left-3 top-3.5 size-4"/><Input aria-label="Search resources" value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a guide, topic, or starting point" className="h-12 pl-10"/></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><article key={r.id} className="flex flex-col border border-border bg-card">{r.imageSlot!=="none"&&<ArtworkPlaceholder slot={r.imageSlot} className="h-64 border-0"/>}<div className="flex flex-1 flex-col p-6"><div className="flex flex-wrap gap-2"><Tag tone={r.officialExternal?"official":"sample"}>{r.officialExternal?"Official Williams":"Sample resource"}</Tag><Tag>{r.readTime}</Tag></div><button onClick={()=>setId(r.id)} className="mt-5 text-left"><h2 className="font-serif text-3xl leading-tight text-primary">{r.title}</h2></button><p className="mb-7 mt-4 text-sm leading-relaxed text-muted-foreground">{r.summary}</p><button onClick={()=>setId(r.id)} className="mt-auto flex min-h-11 items-center justify-between border-t border-border pt-3 text-sm font-medium">Read field note<ArrowUpRight className="size-4"/></button></div></article>)}</div>{!filtered.length&&<EmptyState title="No matching field notes." body="Try a broader topic, such as founder, design, or internship." action={{label:"Clear search",onClick:()=>setQ("")}}/>}</section><ResourceSheet resource={selected} open={!!selected} onOpenChange={v=>!v&&closeDetail()}/></>}
