"use client";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { Menu, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetClose, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { SearchPalette } from "@/components/search/SearchPalette";
const nav = [{to:"/",label:"Commons"},{to:"/network",label:"Network"},{to:"/signal",label:"The Signal"},{to:"/gatherings",label:"Gatherings"},{to:"/resources",label:"Resources"}];
export function Brand(){return <a href="/" className="brand" aria-label="Williams in Technology home"><span className="brand-name">Williams</span><span className="brand-subtitle">in Technology</span></a>;}
export function AppHeader({onShareSignal}:{onShareSignal:()=>void}){
 const[searchOpen,setSearchOpen]=useState(false);const pathname=usePathname();
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true);}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[]);
 return <><header className="sticky top-0 z-40 border-b border-border bg-white"><div className="mx-auto flex h-24 max-w-[96rem] items-center justify-between gap-4 px-5 sm:px-8 lg:px-14"><Brand/><div className="flex items-center gap-2 sm:gap-4"><span className="mr-3 hidden font-mono text-xs uppercase tracking-widest text-muted-foreground xl:block">The Williams technology community</span><Button variant="ghost" size="icon" className="text-primary" onClick={()=>setSearchOpen(true)} aria-label="Search sample community"><Search className="size-6"/></Button><Button className="pill hidden bg-[#b1008e] hover:bg-[#85006b] sm:inline-flex" onClick={onShareSignal}>Share a signal</Button><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="text-primary md:hidden" aria-label="Open navigation"><Menu className="size-6"/></Button></SheetTrigger><SheetContent showCloseButton={false} className="w-[min(92vw,26rem)] bg-paper p-0"><SheetTitle className="sr-only">Navigation</SheetTitle><div className="flex items-center justify-between border-b border-border p-5"><Brand/><SheetClose asChild><Button variant="ghost" size="icon" aria-label="Close navigation"><X/></Button></SheetClose></div><nav aria-label="Mobile navigation" className="grid p-5">{nav.map((item,index)=><a key={item.to} href={item.to} aria-current={pathname===item.to?"page":undefined} className="flex min-h-16 items-center justify-between border-b border-border font-serif text-2xl font-semibold text-primary"><span>{item.label}</span><span className="font-mono text-xs text-muted-foreground">0{index+1}</span></a>)}</nav><div className="grid gap-3 p-5"><SheetClose asChild><Button variant="outline" className="pill" onClick={()=>setSearchOpen(true)}><Search/>Search the community</Button></SheetClose><SheetClose asChild><Button className="pill" onClick={onShareSignal}>Share a signal</Button></SheetClose></div></SheetContent></Sheet></div></div><nav aria-label="Main navigation" className="mx-auto hidden max-w-[96rem] items-center border-t border-border px-8 md:flex lg:px-10">{nav.map(item=><a key={item.to} href={item.to} aria-current={pathname===item.to?"page":undefined} className="main-nav-link">{item.label}</a>)}<span className="ml-auto hidden font-mono text-xs uppercase text-muted-foreground lg:block">Community preview</span></nav></header><SearchPalette open={searchOpen} onOpenChange={setSearchOpen}/></>;
}
