"use client";
import { cloneElement, isValidElement, useId, useRef, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, LoaderCircle, Sparkles } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tag } from "@/components/common/Tag";
import { LocalNotice } from "@/components/common/LocalNotice";
import { extractSignal } from "@/lib/extractSignal";
import { addApprovedSignal, newId } from "@/lib/demoStore";
import { expertiseOptions, cities } from "@/data/seed";
import type { ExtractedSignalFields, ReferralState, SignalCategory, SignalItem } from "@/types/domain";

const example = "My company is looking for an ML intern this summer. Remote is fine and happy to talk with Williams students.";
const empty: ExtractedSignalFields = { type: "", title: "", role: "", location: "", audience: "", referral: "not-confirmed", topics: [], notes: [] };

export function SubmissionFlow({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [step, setStep] = useState(1);
  const [raw, setRaw] = useState(example);
  const [consent, setConsent] = useState(false);
  const [fields, setFields] = useState<ExtractedSignalFields>(empty);
  const [loading, setLoading] = useState(false);
  const [referralConfirmed, setReferralConfirmed] = useState(false);
  const [done, setDone] = useState(false);
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(() => { if (!open) { if(timer.current)clearTimeout(timer.current);setStep(1);setConsent(false);setFields(empty);setDone(false);setLoading(false);setReferralConfirmed(false); } return ()=>{if(timer.current)clearTimeout(timer.current);}; }, [open]);
  const structure = () => { if (!consent || !raw.trim()) return; setLoading(true); timer.current=setTimeout(() => { setFields(extractSignal(raw));setLoading(false);setStep(2); },550); };
  const mutateField = <K extends keyof ExtractedSignalFields>(key: K, value: ExtractedSignalFields[K]) => setFields((current) => ({ ...current, [key]: value }));
  const approve = () => {
    if (!consent || !fields.type || !fields.title.trim()) return;
    const signal: SignalItem = { id: `local-${newId()}`, category: fields.type as SignalCategory, title: fields.title.trim(), role: fields.role || undefined, location: fields.location || "Not specified", city: cities.find(c => fields.location.toLowerCase().includes(c.name.toLowerCase()))?.id, audience: fields.audience || "Not specified", referral: (fields.referral === "available" && !referralConfirmed ? "not-confirmed" : fields.referral) as ReferralState, topics: fields.topics, source: "You · local demo", timestamp: new Date().toISOString(), body: raw, provenance: "Locally approved demo post. Source text was entered on this device.", sample: false, locallyApproved: true };
    addApprovedSignal(signal); setDone(true); setStep(3);
  };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto border border-primary bg-paper p-0 shadow-editorial sm:rounded-sm"><DialogHeader className="border-b border-primary p-5 pr-12 text-left"><div className="flex flex-wrap gap-2"><Tag tone="accent">Local demo only</Tag><Tag>Step {step} / 3</Tag></div><DialogTitle className="mt-3 font-serif text-4xl leading-none text-primary">{step === 1 ? "Share only what you choose." : step === 2 ? "Review every field." : "Added to your demo feed."}</DialogTitle><DialogDescription className="text-sm">Preview: your changes stay in this browser. No message is sent.</DialogDescription></DialogHeader>
    {step === 1 ? <div className="space-y-5 p-5"><div className="border-l-2 border-highlight pl-4"><p className="font-medium">Only messages you choose to share.</p><p className="text-sm text-muted-foreground">Review before anything appears. This prototype never monitors private chats.</p></div><div><Label htmlFor="signal-raw">Message to structure</Label><Textarea id="signal-raw" value={raw} onChange={(event) => { setRaw(event.target.value); setFields(empty); }} className="mt-2 min-h-36 rounded-sm text-base" /></div><label className="flex min-h-14 cursor-pointer items-start gap-3 border border-primary p-4"><Checkbox checked={consent} onCheckedChange={(value) => setConsent(value === true)} className="mt-0.5 size-5" /><span className="text-sm font-medium">I’m sharing my own message or have permission to share it.<span className="mt-1 block font-normal text-muted-foreground">Your permission is required before review.</span></span></label>{!raw.trim() ? <p role="alert" className="text-sm text-destructive">Add a message before continuing.</p> : null}</div> : null}
    {step === 2 ? <div className="page-reveal p-5"><div className="flex flex-wrap items-center justify-between gap-3"><Tag tone="accent">Preview extraction · review every field</Tag><span className="font-mono text-xs text-muted-foreground">Deterministic local parser · not AI</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Type"><select value={fields.type} onChange={(event) => mutateField("type", event.target.value as SignalCategory)} className="h-11 w-full rounded-sm border border-input bg-paper px-3 text-sm"><option value="">Select type</option>{["job", "internship", "founder-request", "ask", "offer", "community"].map((value) => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="Title"><Input value={fields.title} onChange={(event) => mutateField("title", event.target.value)} className="h-11 rounded-sm" /></Field><Field label="Role"><Input value={fields.role} onChange={(event) => mutateField("role", event.target.value)} className="h-11 rounded-sm" placeholder="Unknown" /></Field><Field label="Location"><Input value={fields.location} onChange={(event) => mutateField("location", event.target.value)} className="h-11 rounded-sm" placeholder="Unknown" /></Field><Field label="Audience"><Input value={fields.audience} onChange={(event) => mutateField("audience", event.target.value)} className="h-11 rounded-sm" placeholder="Unknown" /></Field><Field label="Referral"><select value={fields.referral} onChange={(event) => { mutateField("referral", event.target.value as ReferralState); setReferralConfirmed(false); }} className="h-11 w-full rounded-sm border border-input bg-paper px-3 text-sm"><option value="not-confirmed">Not confirmed</option><option value="available">Available — confirm below</option><option value="not-offered">Not offered</option></select></Field></div><div className="mt-4"><p className="font-mono text-xs uppercase text-muted-foreground">Topics · select to edit</p><div className="mt-2 flex flex-wrap gap-2">{expertiseOptions.map(topic=><Button key={topic} size="sm" variant={fields.topics.includes(topic)?"default":"outline"} aria-pressed={fields.topics.includes(topic)} onClick={()=>mutateField("topics",fields.topics.includes(topic)?fields.topics.filter(t=>t!==topic):[...fields.topics,topic])}>{topic}</Button>)}</div></div>{fields.notes.map((note) => <p key={note} className="mt-3 border-l-2 border-highlight pl-3 text-sm text-muted-foreground">{note}</p>)}{fields.referral === "available" ? <label className="mt-5 flex min-h-12 cursor-pointer items-center gap-3 border border-primary p-3"><Checkbox checked={referralConfirmed} onCheckedChange={(value) => setReferralConfirmed(value === true)} /><span className="text-sm">I confirm this message explicitly offers a referral.</span></label> : null}<p className="mt-5 border-t border-border pt-4 font-mono text-xs text-muted-foreground">Raw text · {raw}</p></div> : null}
    {step === 3 ? <div className="p-7 text-center"><div className="mx-auto grid size-14 place-items-center border border-primary bg-highlight"><Check /></div><p className="mt-5 font-serif text-3xl text-primary">Your sample row is now in The Signal.</p><p className="mx-auto mt-3 max-w-lg text-sm text-muted-foreground">Approved and saved on this device only. Nothing was sent, published, emailed, or submitted.</p><div className="mt-5 flex justify-center"><LocalNotice /></div></div> : null}
    <DialogFooter className="gap-2 border-t border-primary p-5 sm:space-x-0">{step === 2 ? <Button variant="outline" onClick={() => setStep(1)} className="rounded-sm"><ArrowLeft />Back</Button> : null}<Button variant="ghost" onClick={() => onOpenChange(false)} className="rounded-sm">{done ? "Close" : "Cancel"}</Button>{step === 1 ? <Button onClick={structure} disabled={!consent || !raw.trim() || loading} className="rounded-sm">{loading ? <LoaderCircle className="animate-spin" /> : <Sparkles />}{loading ? "Structuring locally…" : "Structure message"}</Button> : null}{step === 2 ? <Button onClick={approve} disabled={!consent || !fields.type || !fields.title.trim() || (fields.referral === "available" && !referralConfirmed)} className="rounded-sm">Approve & add to demo feed<ArrowRight /></Button> : null}</DialogFooter>
  </DialogContent></Dialog>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { const id=useId();return <div><Label htmlFor={id} className="mb-2 block font-mono text-xs uppercase text-muted-foreground">{label}</Label>{isValidElement<{id?:string}>(children)?cloneElement(children,{id}):children}</div>; }

