import {cities,gatherings,people,resources,signals,startups} from "@/data/seed";
import type {SearchResult,SignalItem} from "@/types/domain";
const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();
const cityText=(id?:string)=>cities.find(c=>c.id===id)?.name??"";
const conceptRules:Array<[RegExp,string,string[]]>=[[/\b(ai|ml|machine learning)\b/,"AI / ML",["ai","ml","machine learning"]],[/cyber|security/,"Cybersecurity",["cybersecurity","security","appsec"]],[/healthcare|healthtech|clinical/,"Healthcare",["healthcare","healthtech","clinical"]],[/\bsales|gtm|go to market/,"Sales",["sales","go to market","gtm"]],[/\bintern/,"Internships",["intern","internship","internships"]],[/engineer|developer/,"Engineering",["engineer","engineers","engineering","developer"]],[/\bclimate/,"Climate",["climate","carbon","energy"]]];
function parse(query:string){const q=normalize(query);const city=/\bboston\b/.test(q)?"boston":/\b(sf|san francisco|bay area)\b/.test(q)?"san-francisco":/\b(nyc|new york)\b/.test(q)?"new-york":/\bwilliamstown\b/.test(q)?"williamstown":undefined;const concepts=conceptRules.filter(([re])=>re.test(q));const seeking=/looking for|seeking|hiring/.test(q);const intent=/\b(event|events|upcoming|dinner|gathering)\b/.test(q)?"events":/\bintern/.test(q)||seeking?"signals":/\b(people|alumni|founder|founders|mentor)\b/.test(q)?"people":null;return {q,city,concepts,seeking,intent};}
const matches=(hay:string,words:string[])=>words.some(word=>new RegExp(`\\b${word}\\b`).test(hay));
export function searchCommunity(query:string,approved:SignalItem[]=[]):SearchResult[]{const {q,city,concepts,intent,seeking}=parse(query);if(!q)return [];const results:SearchResult[]=[];const ignored=new Set(["in","who","can","help","with","the","a","an","and","for","me","williams","students","people","alumni","founder","founders","startup","startups","summer","upcoming","events","event","looking","seeking","boston","new","york","san","francisco","sf","nyc"]);const words=q.split(" ").filter(w=>!ignored.has(w)&&w.length>1);
const add=(result:Omit<SearchResult,"score">,haystack:string,itemCity?:string,bonus=0)=>{const hay=normalize(haystack);if(city&&itemCity!==city&&!hay.includes(normalize(cityText(city))))return;if(concepts.length&&!concepts.every(([, ,syn])=>matches(hay,syn)))return;const hits=words.filter(w=>hay.includes(w)).length;if(!concepts.length&&!intent&&words.length>0&&!words.every(w=>hay.includes(w))&&!hay.includes(q))return;results.push({...result,score:bonus+hits*2+(hay.includes(q)?12:0)+(result.type===intent?15:0)});};
if(intent!=="events"&&intent!=="signals")for(const p of people){if(/\balumni\b/.test(q)&&p.kind!=="alumni")continue;if(/\bfounders?\b/.test(q)&&p.kind!=="founder")continue;add({id:p.id,type:"people",title:p.name,subtitle:`${p.role} · ${cityText(p.city)}`,route:"/network",chips:[p.kind,cityText(p.city),...p.expertise.slice(0,2)]},[p.name,p.role,p.kind,p.bio,...p.expertise,...p.asks,...p.offers].join(" "),p.city,4);}
if(intent!=="events"&&!/\balumni\b/.test(q)&&!concepts.some(c=>c[1]==="Internships"))for(const s of startups){add({id:s.id,type:"startups",title:s.name,subtitle:`${s.stage} · ${cityText(s.city)}`,route:"/network",chips:[s.sector,cityText(s.city)]},[s.name,s.sector,s.summary,...s.asks,...s.founderIds.flatMap(id=>people.find(p=>p.id===id)?.expertise??[])].join(" "),s.city,seeking?7:0);}
if(intent!=="events"&&intent!=="people")for(const s of [...approved,...signals]){if(concepts.some(c=>c[1]==="Internships")&&s.category!=="internship")continue;add({id:s.id,type:"signals",title:s.title,subtitle:`${s.location} · ${s.source}`,route:"/signal",chips:[s.category,...s.topics.slice(0,2)]},[s.title,s.role,s.company,s.category,s.location,s.audience,...s.topics,s.body].join(" "),s.city,4);}
if(!intent||intent==="events")for(const e of gatherings)add({id:e.id,type:"events",title:e.title,subtitle:`${cityText(e.city)} · ${new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",timeZone:e.timezone}).format(new Date(e.date))}`,route:"/gatherings",chips:[cityText(e.city),"proposed sample"]},[e.title,e.summary,e.venue,...e.agenda].join(" "),e.city);
if(!intent)for(const r of resources)add({id:r.id,type:"resources",title:r.title,subtitle:r.officialExternal?"Official external reading":r.category,route:"/resources",chips:[r.category]},[r.title,r.category,r.summary,...r.body].join(" "));
return results.sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,24);}
export function queryChips(query:string){const {q,city,concepts}=parse(query);return [city?cityText(city):"",...concepts.map(c=>c[1]),/\bfounders?\b/.test(q)?"Founders":"",/\balumni\b/.test(q)?"Alumni":""].filter(Boolean);}
